module.exports = {
    USER           : "plugin::users-permissions.user",
    ROLE           : "plugin::users-permissions.role",
    LOAD           : "api::load.load",
    DISPATCHER_SHIFT : "api::dispatcher-shift.dispatcher-shift",
    BOMB           : "api::bomb.bomb",
    BANNER         : "api::banner.banner",
    FISCAL         : "api::fiscal.fiscal",
    VEHICLE        : "api::vehicle.vehicle",
    FLEET          : "api::fleet.fleet",
    CUSTOMER_LEVEL : "api::customer-level.customer-level",
    FLEET_LEVEL    : "api::fleet-level.fleet-level",
    PROMOTION      : "api::promotion.promotion",
    ADMIN_REPORT   : "api::admin-report.admin-report",
    ADMIN_PROMOTION : "api::admin-promotion.admin-promotion",
    ADMIN_BANNER   : "api::admin-banner.admin-banner",
}
